name: stg Deploy

on:
  workflow_run:
    workflows:
      - CI
    branches: [master]
    types:
      - completed

jobs:
  test-step:
    name: output

    runs-on: ubuntu-latest
    steps:
      - name: output
        run: echo tag111
