name: stg Deploy

# on:
#  push:
#    tags:
#      - "20[0-9]+.[0-9]+.[0-9]+" # Needs to match the format year.month.index (e.g. 2021.10.0)

jobs:
  test-step:
    name: output

    runs-on: ubuntu-latest
    steps:
      - name: output
        run: echo tag111
