name: Release TAG

on:
  workflow_dispatch:

jobs:
  create-tag:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: push a tag
        run: |
          git tag 2021.10.0
          git push origin 2021.10.0
